spring:
  application:
    name: JoseVilla-Aplazo-Challenge
  profiles:
    active: localhost

  datasource:
    url: jdbc:postgresql://postgres:5432/postgres #jdbc:postgresql://localhost:5432/postgres -> para local sin docker
    username: postgres
    password: camilo300zx
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: YWxwaGExMjM0NTY3ODkwYWJjZGVmZ2hpamtsbW5vcA==

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"